title: Moh Ravi Dwi Putra
email: ravidwiputra@gmail.com
github_username: rdp77
author: Moh Ravi Dwi Putra
description: >-
  Moh Ravi Dwi Putra's profile website, which contains important information 
  about him such as your resume, portfolio, awards, certification, and contact.
keywords:
  Moh Ravi Dwi Putra, Rafi Dwi Putra, Profile Ravi, Profile Rafi, Profile Website, Resume,
  Portfolio, Awards, Certification, and contact
copyright: Make it as beautiful and functional as possible.
social:
  name: Moh Ravi Dwi Putra
  links:
    - https://github.com/rdp77
    - https://facebook.com/ravidwiputra77
    - https://www.linkedin.com/in/moh-ravi-dwi-putra/
    - https://www.instagram.com/raviravdp/
    - https://www.youtube.com/channel/UCgy1w-3_8D1VMfarucu2lrA
url: https://ravidwiputra.my.id
permalink: pretty
lang: en_ID
google_site_verification: 23XGywZf8ZI_3Rr2eQBwH54Sp5IUp_wDNDUCnDohTpc
logo: /assets/img/avatar.png
image: /assets/img/avatar.png
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
