title: Moh Ravi Dwi Putra
email: ravidwiputra@gmail.com
github_username: rdp77
author: Moh Ravi Dwi Putra
description: >-
  Moh Ravi Dwi Putra's profile website, which contains important information 
  about him such as your resume, portfolio, awards, certification, and contact.
keywords:
  Moh Ravi Dwi Putra, Rafi Dwi Putra, Profile Ravi, Profile Rafi, Profile Website, Resume,
  Portfolio, Awards, Certification, and contact
copyright: Make it as beautiful and functional as possible.
social:
  name: Moh Ravi Dwi Putra
  links:
    - https://github.com/rdp77
    - https://facebook.com/ravidwiputra77
    - https://www.linkedin.com/in/rdp77/
    - https://www.instagram.com/raviravdp/
    - https://www.youtube.com/@ravidwiputra77
url: https://ravidwiputra.my.id
lang: en_US
google_site_verification: 8FB68inDTkKFOhWeQv2l6zfpF7oYJEn6wqZDOTDd6dk
twitter:
  username: ravi77__
  card: summary
facebook:
  app_id: 273593853241776
  publisher: https://facebook.com/ravidwiputra77
  admins: 100003118966989
logo: /assets/img/avatar.png
image: /assets/img/avatar.png
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
